"""Adiciona campo is_active a User

Revision ID: 769282b54f7d
Revises: 2f799c8cbb57
Create Date: 2025-09-26 10:21:26.662476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769282b54f7d'
down_revision = '2f799c8cbb57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
